bookkeeping_site/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Page.as_view(), name='index'),
    path('manual/', Manual.as_view(), name='manual'),
    # Регистрация и Авторизация
    path('login/', user_login, name='login'),
    path('logout', user_logout, name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    # Счета
    path('accounts/', AccountPage.as_view(), name='accounts'),
    path('accounts/create/', AccountCreate.as_view(), name='create_account'),
    path('accounts/update/<int:pk>/', AccountUpdate.as_view(), name='update_account'),
    path('accounts/transfer/', AccountTransfer.as_view(), name='transfer_account'),
    path('accounts/delete/<int:pk>/', AccountDelete.as_view(), name='delete_account'),
    # Доходы
    path('incomes/', IncomePage.as_view(), name='incomes'),
    path('incomes/create/', IncomeCreate.as_view(), name='create_income'),
    path('incomes/update/<int:pk>/', IncomeUpdate.as_view(), name='update_income'),
    path('incomes/delete/<int:pk>/', IncomeDelete.as_view(), name='delete_income'),
    # Расходы
    path('expenses/', ExpensePage.as_view(), name='expenses'),
    path('expenses/create/', ExpenseCreate.as_view(), name='create_expense'),
    path('expenses/update/<int:pk>/', ExpenseUpdate.as_view(), name='update_expense'),
    path('expenses/delete/<int:pk>/', ExpenseDelete.as_view(), name='delete_expense'),
    # Долги пользователя
    path('owe_debts/', OweDebtPage.as_view(), name='owe_debts'), 
    path('owe_debts/create/', OweDebtCreate.as_view(), name='create_owe_debt'),    
    path('owe_debts/update/<int:pk>/', OweDebtUpdate.as_view(), name='update_owe_debt'),
    path('owe_debts/return/<int:pk>/', OweDebtReturn.as_view(), name='return_owe_debt'), 
    path('owe_debts/delete/<int:pk>/', OweDebtDelete.as_view(), name='delete_owe_debt'),   
    # Долги у пользователя
    path('debts/', DebtPage.as_view(), name='debts'), 
    path('debts/create/', DebtCreate.as_view(), name='create_debt'),    
    path('debts/update/<int:pk>/', DebtUpdate.as_view(), name='update_debt'),
    path('debts/return/<int:pk>/', DebtReturn.as_view(), name='return_debt'), 
    path('debts/delete/<int:pk>/', DebtDelete.as_view(), name='delete_debt'),  
    # Статистика
    path('graphic/accounts/', graph_accounts, name='graphic_accounts'), 
    path('graphic/incomes/', graph_incomes, name='graphic_incomes'), 
    path('graphic/expenses/', graph_expenses, name='graphic_expenses'), 
    ## Категории
    path('categories/accounts/', CategoryAccountPage.as_view(), name='categories_accounts'), 
    path('categories/accounts/create/', CategoryAccountCreate.as_view(), name='create_category_account'), 
    path('categories/accounts/update/<int:pk>/', CategoryAccountUpdate.as_view(), name='update_category_account'), 
    path('categories/accounts/delete/<int:pk>/', CategoryAccountDelete.as_view(), name='delete_category_account'),  
    # 
    path('categories/incomes/', CategoryIncomePage.as_view(), name='categories_incomes'),
    path('categories/incomes/create/', CategoryIncomeCreate.as_view(), name='create_category_income'), 
    path('categories/incomes/update/<int:pk>/', CategoryIncomeUpdate.as_view(), name='update_category_income'), 
    path('categories/incomes/delete/<int:pk>/', CategoryIncomeDelete.as_view(), name='delete_category_income'),  
    # 
    path('categories/expenses/', CategoryExpensePage.as_view(), name='categories_expenses'), 
    path('categories/expenses/create/', CategoryExpenseCreate.as_view(), name='create_category_expense'), 
    path('categories/expenses/update/<int:pk>/', CategoryExpenseUpdate.as_view(), name='update_category_expense'), 
    path('categories/expenses/delete/<int:pk>/', CategoryExpenseDelete.as_view(), name='delete_category_expense'),  
    #
    path('categories/currencys/', CategoryCurrencyPage.as_view(), name='categories_currencys'), 
    path('categories/currencys/create/', CategoryCurrencyCreate.as_view(), name='create_category_currency'), 
    path('categories/currencys/update/<int:pk>/', CategoryCurrencyUpdate.as_view(), name='update_category_currency'), 
    path('categories/currencys/delete/<int:pk>/', CategoryCurrencyDelete.as_view(), name='delete_category_currency'),  
]

conf/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookkeeping_site.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookkeeping_site/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class CategoriesIncomes(models.Model):
    """Категории доходов по дефолту"""
    user = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name='Пользователь'
    )
    title = models.CharField(
        max_length=70, 
        verbose_name='Название категории дохода'
    )
    subcategory = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name='Категория',
    )
    def __str__(self):
        """Строковое представление"""
        return self.title
    
    def __repr__(self):
        """Подобие строкового представления"""
        return f'Категория: pk={self.pk}, title={self.title}, subcategory={self.subcategory}'
    
    class Meta:
        """Характер Класса"""
        verbose_name = 'Категория Дохода'
        verbose_name_plural = 'Категории Доходов'

class CategoriesExpenses(models.Model):
    """Категории расходов по дефолту"""
    user = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name='Пользователь'
    )
    title = models.CharField(
        max_length=70, 
        verbose_name='Название категории расхода'
    )
    subcategory = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name='Категория',
    )
    def __str__(self):
        """Строковое представление"""
        return self.title
    
    def __repr__(self):
        """Подобие строкового представления"""
        return f'Категория: pk={self.pk}, title={self.title}, subcategory={self.subcategory}'
    
    class Meta:
        """Характер Класса"""
        verbose_name = 'Категория Расхода'
        verbose_name_plural = 'Категории Расходов'

class CategoriesCurrencys(models.Model):
    """Категории единиц валют"""
    user = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name='Пользователь'
    )
    title = models.CharField(
        max_length=70, 
        verbose_name='Название категории валюты'
    )
    course = models.FloatField(
        default=0,
        null=False,
        verbose_name='Курс'
    )
    def __str__(self):
        """Строковое представление"""
        return self.title
    
    def __repr__(self):
        """Подобие строкового представления"""
        return f'Категория: pk={self.pk}, title={self.title}, course={self.course}'
    
    class Meta:
        """Характер Класса"""
        verbose_name = 'Категория Валюты'
        verbose_name_plural = 'Категории Валют'

class CategoriesAccounts(models.Model):
    """Категории счетов по дефолту"""
    user = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name='Пользователь'
    )
    title = models.CharField(
        max_length=70, 
        verbose_name='Название категории'
    )
    def __str__(self):
        """Строковое представление"""
        return str(self.title)

    def __repr__(self):
        """Подобие строкового представления"""
        return f'Категория: pk={self.pk}, title={self.title}'

    class Meta:
        """Характер Класса"""
        verbose_name = 'Категория Счета'
        verbose_name_plural = 'Категории Счетов'

class UserAccounts(models.Model):
    """Счета пользователя"""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Пользователь'
    )
    account = models.ForeignKey(
        CategoriesAccounts,
        on_delete=models.OneToOneField,
        null=False,
        verbose_name='Cчета'
    )
    currency = models.ForeignKey(
        CategoriesCurrencys,
        null=False,
        on_delete=models.CASCADE,
        verbose_name='Валюта'
    )
    sum = models.IntegerField(
        verbose_name='Сумма'
    )

    def get_absolute_url(self): 
        """Ссылка на страницу"""
        return reverse('update_account', args=[str(self.id)])

    def __str__(self):
        """Строковое представление"""
        return self.account.title
    
    def __repr__(self):
        """Подобие строкового представления"""
        return f'Счет: pk={self.pk}, account={self.account}, course={self.currency.course}, currency={self.currency}, sum={self.sum}'

    class Meta:
        """Характер Класса"""
        verbose_name = 'Счет Пользователя'
        verbose_name_plural = 'Счета Пользователя'

    @property # используется для создания <<специальной>> функциональности определеным методам
    def get_total_sum(self):
        """Получение полной суммы счета с учетом курса валют"""
        sum = self.sum
        course = self.currency.course
        return course*sum
    
class UserExpenses(models.Model):
    """Расходы пользователя"""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE, 
        verbose_name='Пользователь'
    )
    category = models.ForeignKey(
        CategoriesExpenses,
        related_name='category_expenses',
        on_delete=models.CASCADE, 
        verbose_name='Категория'
    )
    subcategory = models.ForeignKey(
        CategoriesExpenses,
        related_name='subcategory_expenses',
        on_delete=models.CASCADE, 
        verbose_name='Подкатегория',
        null=True,
        blank=True
    )
    account = models.ForeignKey(
        UserAccounts,
        on_delete=models.CASCADE,
        verbose_name='Счет'
    )
    comment = models.CharField(
        max_length=20,
        null=True,
        blank=True,
        verbose_name='Коментарий'
    )
    currency = models.ForeignKey(
        CategoriesCurrencys,
        on_delete=models.CASCADE,
        verbose_name='Валюта'
    )
    sum = models.IntegerField(
        verbose_name='Сумма'
    )
    created_at = models.DateField(
        verbose_name='Дата'
    )

    def get_absolute_url(self): 
        """Ссылка на страницу"""
        return reverse('update_expense', args=[str(self.id)])

    def __str__(self):
        """Строковое представление"""
        return self.user.username

    def __repr__(self):
        """Подобие строкового представления"""
        return f'Расход: pk={self.pk}, category={self.category}, subcategory={self.subcategory}, account={self.account}, currency={self.currency} sum={self.sum}'

    class Meta:
        """Характер Класса"""
        verbose_name = 'Расход пользователя'
        verbose_name_plural = 'Расходы пользователя'

    @property
    def get_total_sum(self):
        """Получение полной суммы расхода"""
        sum = self.sum
        currency = self.currency.course
        return sum * currency
    
    @property
    def get_title_category(self):
        """Title для графика"""
        return self.category.title + '-' + self.currency.title
    
    @property
    def get_title_subcategory(self):
        """Title для графика"""
        return self.subcategory.title + '-' + self.currency.title
    
class UserIncomes(models.Model):
    """Доходы пользователя"""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE, 
        verbose_name='Пользователь'
    )
    category = models.ForeignKey(
        CategoriesIncomes,
        related_name='category_incomes',
        on_delete=models.CASCADE, 
        verbose_name='Категория'
    )
    subcategory = models.ForeignKey(
        CategoriesIncomes,
        related_name='subcategory_incomes',
        on_delete=models.CASCADE, 
        verbose_name='Подкатегория',
        null=True,
        blank=True
    )
    account = models.ForeignKey(
        UserAccounts,
        on_delete=models.CASCADE,
        verbose_name='Счет'
    )
    comment = models.CharField(
        max_length=20,
        null=True,
        blank=True,
        verbose_name='Коментарий'
    )
    currency = models.ForeignKey(
        CategoriesCurrencys,
        on_delete=models.CASCADE,
        verbose_name='Валюта'
    )
    sum = models.IntegerField(
        verbose_name='Сумма'
    )
    created_at = models.DateField(
        verbose_name='Дата'
    )

    def get_absolute_url(self): 
        """Ссылка на страницу"""
        return reverse('update_income', args=[str(self.id)])

    def __str__(self):
        """Строковое представление"""
        return self.user.username

    def __repr__(self):
        """Подобие строкового представления"""
        return f'Доходы: pk={self.pk}, category={self.category}, subcategory={self.subcategory}, account={self.account}, currency={self.currency} sum={self.sum}'
    
    class Meta:
        """Характер Класса"""
        verbose_name = 'Доходы пользователя'
        verbose_name_plural = 'Доходы Пользователя'
    
    @property
    def get_total_sum(self):
        """Получение полной суммы дохода"""
        sum = self.sum
        currency = self.currency.course
        return sum * currency
    
    @property
    def get_title_category(self):
        """Title для графика"""
        return self.category.title + '-' + self.currency.title
    
    @property
    def get_title_subcategory(self):
        """Title для графика"""
        return self.subcategory.title + '-' + self.currency.title
    
class UserTransferToAccount(models.Model):
    """Переводы пользователя с счета на счет"""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Пользователь'
    )
    account1 = models.ForeignKey(
        UserAccounts,
        on_delete=models.CASCADE,
        related_name='account1',
        null=False,
        verbose_name='C счета'
    )
    account2 = models.ForeignKey(
        UserAccounts,
        on_delete=models.CASCADE,
        related_name='account2',
        null=False,
        verbose_name='На счет счета'
    )
    currency = models.ForeignKey(
        CategoriesCurrencys,
        on_delete=models.CASCADE,

bookkeeping_site/templates/bookkeeping/accounts/create_account.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block main %}
<div class="content-wrapper" style="min-height: 700.895px;">
    <div class="content border-bottom mb-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-md-auto d-flex flex-grow-1 align-items-center">
                    <h1 class="h4 m-0 pr-3 mr-3 border-right">
                      {{ title }}
                    </h1>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'index' %}">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'accounts' %}">Счета</a></li>
                        <li class="breadcrumb-item active">
                            {{ title }}
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
      {% include 'bookkeeping/components/_message.html' %}     
      <div class="container-fluid">
          <section id="content" class="content">
              <form method="post" novalidate="">
                {% csrf_token %}
                <div class="row"><div class="col-12 col-lg-9"><div class="card"><div class="card-body">
                  <div class="form-group">
                    <div class="row">
                        <label class="col-sm-3 text-left" for="id_user">
                            {{ form.account.label }}
                        <span class="text-red">* </span>
                        </label>
                        <div class=" col-sm-7 field-user">
                            <div class="related-widget-wrapper">
                                {{ form.account }}
                                </span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                                <a class="related-widget-wrapper-link add-related" data-popup="yes" href="{% url 'create_category_account' %}" title="Добавить счет"><img src="/static/admin/img/icon-addlink.svg" alt="Добавить"></a>
                            </div>
                            <div class="help-block text-red">
                                {{ form.account.errors }}
                            </div>
                        </div>
                    </div>
                  </div>
                  <div class="form-group">
                      <div class="row">
                        <label class="col-sm-3 text-left">
                            {{ form.currency.label }}
                          <span class="text-red">* </span>
                        </label>
                        <div class=" col-sm-7">
                            <div class="related-widget-wrapper">
                                {{ form.currency }}
                                </span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                                <a class="related-widget-wrapper-link add-related" data-popup="yes" href="{% url 'create_category_currency' %}"title="Добавить валюту"><img src="/static/admin/img/icon-addlink.svg" alt="Добавить"></a>
                            </div>
                            <div class="help-block text-red">
                                {{ form.currency.errors }}
                            </div>
                        </div>
                      </div>
                  </div>
                  <div class="form-group">
                        <div class="row">
                            <label class="col-sm-3 text-left">
                                {{ form.sum.label }}
                                <span class="text-red">* </span>
                            </label>
                            <div class=" col-sm-7">
                                <div class="related-widget-wrapper">
                                    {{ form.sum }}
                                </div>
                                <div class="help-block text-red">
                                    {{ form.sum.errors }}
                                </div>
                            </div>
                            
                        </div>
                  </div>
                </div></div></div>
                <div class="col-12 col-lg-3">
                  <div class="form-group">
                    <input type="submit" value="Сохранить" class="btn btn-success form-control">
                  </div>
                  <div class="form-group">
                    <a href="{% url 'accounts' %}" class="btn btn-info form-control">Отмена</a>
                  </div>
                </div>
              </div>
              </form>
          </section>
      </div>
    </div>
</div>
{% endblock main %}

bookkeeping_site/templates/bookkeeping/accounts/transfer_to_account.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block main %}
<div class="content-wrapper" style="min-height: 700.895px;">
    <div class="content border-bottom mb-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-md-auto d-flex flex-grow-1 align-items-center">
                    <h1 class="h4 m-0 pr-3 mr-3 border-right">
                        {{ title }}
                    </h1>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'index' %}">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'accounts' %}">Счета</a></li>
                        <li class="breadcrumb-item active">
                            {{ title }}
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        {% include 'bookkeeping/components/_message.html' %}     
        <div class="container-fluid">
            <section id="content" class="content">
            <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row"><div class="col-12 col-lg-9"><div class="card"><div class="card-body">
                            <div class="form-group">
                                <div class="row">
                                <label class="col-sm-3 text-left" for="id_user">
                                    {{ form.account1.label }}
                                    <span class="text-red">* </span>
                                </label>
                                <div class=" col-sm-7 field-user">
                                    <div class="related-widget-wrapper">
                                        {{ form.account1 }}
                                        </span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                                        <a class="related-widget-wrapper-link add-related" data-popup="yes" href="{% url 'create_category_account' %}" title="Добавить счет"><img src="/static/admin/img/icon-addlink.svg" alt="Добавить"></a>
                                    </div>
                                    <div class="help-block text-red">
                                        {{ form.account1.errors }}
                                    </div>
                                </div>
                            </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                <label class="col-sm-3 text-left" for="id_user">
                                    {{ form.account2.label }}
                                    <span class="text-red">* </span>
                                </label>
                                <div class=" col-sm-7 field-user">
                                    <div class="related-widget-wrapper">
                                        {{ form.account2 }}
                                        </span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                                        <a class="related-widget-wrapper-link add-related" data-popup="yes" href="{% url 'create_category_account' %}" title="Добавить счет"><img src="/static/admin/img/icon-addlink.svg" alt="Добавить"></a>
                                    </div>
                                    <div class="help-block text-red">
                                        {{ form.account2.errors }}
                                    </div>
                                </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                <label class="col-sm-3 text-left" for="id_user">
                                    {{ form.currency.label }}
                                    <span class="text-red">* </span>
                                </label>
                                <div class=" col-sm-7 field-user">
                                    <div class="related-widget-wrapper">
                                        {{ form.currency }}
                                        </span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                                        <a class="related-widget-wrapper-link add-related" data-popup="yes" href="{% url 'create_category_currency' %}" title="Добавить счет"><img src="/static/admin/img/icon-addlink.svg" alt="Добавить"></a>
                                    </div>
                                    <div class="help-block text-red">
                                        {{ form.currency.errors }}
                                    </div>
                                </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <label class="col-sm-3 text-left">
                                        {{ form.sum.label }}
                                        <span class="text-red">* </span>
                                    </label>
                                    <div class=" col-sm-7">
                                        <div class="related-widget-wrapper">
                                            {{ form.sum }}
                                        </div>
                                        <div class="help-block text-red">
                                            {{ form.sum.errors }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                    <div class="col-12 col-lg-3">
                    <div class="form-group">
                        <input type="submit" value="Сохранить" class="btn btn-success form-control">
                    </div>
                    <div class="form-group">
                        <a href="{% url 'accounts' %}" class="btn btn-info form-control">Отмена</a>
                    </div>
                    </div>
                </div>
            </form>
            </section>
        </div>
    </div>
</div>
{% endblock main %}

bookkeeping_site/templates/bookkeeping/accounts/update_account.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block main %}
<div class="content-wrapper" style="min-height: 700.895px;">
    <div class="content border-bottom mb-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-md-auto d-flex flex-grow-1 align-items-center">
                    <h1 class="h4 m-0 pr-3 mr-3 border-right">
                        {{ title }}
                    </h1>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'index' %}">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'accounts' %}">Счета</a></li>
                        <li class="breadcrumb-item active">
                            {{ title }}
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        {% include 'bookkeeping/components/_message.html' %}     
        <div class="container-fluid">
            <section id="content" class="content">
                <form method="post" novalidate="">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12 col-lg-9"><div class="card"><div class="card-body">
                        <div class="form-group">
                            <div class="row">
                              <label class="col-sm-3 text-left" for="id_user">
                                  {{ form.account.label }}
                                <span class="text-red">* </span>
                              </label>
                            <div class=" col-sm-7">
                                <div class="related-widget-wrapper">
                                    {{ form.account }}
                                    </span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                                    <a class="related-widget-wrapper-link add-related" data-popup="yes" href="{% url 'create_category_account' %}" title="Добавить валюту"><img src="/static/admin/img/icon-addlink.svg" alt="Добавить"></a>
                                </div>
                                  <div class="help-block text-red">
                                    {{ form.account.errors }}
                                  </div>
                              </div>
                            </div>
                        </div>
                        <div class="form-group">
                          <div class="row">
                            <label class="col-sm-3 text-left">
                                {{ form.currency.label }}
                              <span class="text-red">* </span>
                            </label>
                            <div class=" col-sm-7">
                                <div class="related-widget-wrapper">
                                    {{ form.currency }}
                                    </span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                                    <a class="related-widget-wrapper-link add-related" data-popup="yes" href="{% url 'create_category_currency' %}" title="Добавить валюту"><img src="/static/admin/img/icon-addlink.svg" alt="Добавить"></a>
                                </div>
                                <div class="help-block text-red">
                                    {{ form.currency.errors }}
                                </div>
                            </div>
                          </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                              <label class="col-sm-3 text-left" for="id_user">
                                  {{ form.sum.label }}
                                <span class="text-red">* </span>
                              </label>
                            <div class=" col-sm-7">
                                <div class="related-widget-wrapper">
                                    {{ form.sum }}
                                </div>
                                  <div class="help-block text-red">
                                    {{ form.sum.errors }}
                                  </div>
                              </div>
                            </div>
                        </div>
                      </div>
                    </div>
                    </div>
                    <div class="col-12 col-lg-3">
                    <div class="form-group">
                        <input type="submit" value="Сохранить" class="btn btn-success form-control">
                    </div>
                    <div class="form-group">
                        <a href="{% url 'delete_account' account.pk %}" class="btn btn-danger form-control">Удалить</a>
                    </div>
                    <div class="form-group">
                        <a href="{% url 'accounts' %}" class="btn btn-info form-control">Отмена</a>
                    </div>
                    </div>
                </div>
                </form>
            </section>
        </div>
    </div>
</div>

{% endblock main %}